
package learn;

/**
 * Represents loss functions.
 * @author connor
 *
 */
public interface LossFunction {
	
	/**
	 * Calculate the loss function between two sets of data.
	 * @param generated The set generated by a regression or other thing.
	 * @param expected The set of values that are to be expected.
	 * @return The total loss function.
	 */
	double loss(double[] generated, double[] expected);
}
